name: CI
on: [push]
jobs:
#  unit_test_job:
#    name: Unit Tests
#    runs-on: ubuntu-latest
#    steps:
#      # Checks out a copy of your repository
#      - name: Checkout Repository
#        uses: actions/checkout@v1
#
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#
#      - name: Unit Test
#        run: ./gradlew --stacktrace testRelease

  android_tests:
    runs-on: [ macos-latest ]
#    strategy:
#      matrix:
#        api-level: [29]
#        profile: [Pixel 4]
    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
#          api-level: ${{ matrix.api-level }}
          api-level: 29
#          target: default
#          arch: x86_64
#          profile: avdmanager list
#          script: ./gradlew connectedAndroidTest
          script: $ANDROID_HOME/tools/bin/avdmanager list