name: CI
on: [pull_request]
jobs:
  unit_test_job:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit Tests
        run: ./gradlew --stacktrace testRelease

  android_test_job:
    name: Integration Tests
    runs-on: macos-latest
#    strategy:
#      matrix:
#        api-level: [29, 30]
#        profile: [Nexus 6, Pixel 4]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
#          api-level: ${{ matrix.api-level }}
          api-level: 29
          profile: Nexus 6
#          profile: ${{ matrix.profile }}
          script: ./gradlew connectedAndroidTest
#          script: avdmanager list